version: '3.8'
services:
  redis:
    image: "redis:alpine"

  web:
    restart: unless-stopped
    build: .
    expose:
      - 8000
    volumes:
      - static:/usr/src/app/posts/static
      - media:/usr/src/app/posts/media

  nginx:
    restart: unless-stopped
    container_name: redis_django
    build: .nginx
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - web

volumes:
  static:
  media: