name: Deploy

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/redis_edu"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
    
  redis_install:

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: setup redis
        run: |
          sudo apt install redis-server
          if [[ "$( echo 'ping' | /usr/bin/redis-cli )" == "PONG" ]] ; then
              echo "ping worked"
          else
              echo "ping FAILED"
          fi
          systemctl status redis
          systemctl status redis-server
          exit 0
